### ISSUE TITLE
How to specify the security group?

### ISSUE THREAD

**Issue by avemeva** [yandex-cloud/docker-machine-driver-yandex#11]
How to specify the security group during the creation of docker-machine?

As far as I understand change of security group after creation is not allowed.

**Comment by GennadySpb** [comment]
Hi @andrewshvv !
Check this release - https://github.com/yandex-cloud/docker-machine-driver-yandex/releases/tag/v0.1.26-rc - it's contains Security Group support.

**Comment by avemeva** [comment]
Confirming it is working. Thanks!

Future note for others - you have to specify an ID, not the name of the security group.
